[package]
name = "gff_diff"
version = "0.1.0"
authors = ["Magnus Manske <magnusmanske@googlemail.com>"]
edition = "2018"

[dependencies]
bio = "*"
json = "0.11.13"
serde_json = "1.0"
multimap = "0.4.0"

[profile.dev]
opt-level = 3